GET http://localhost:8000/v1/planets

### 

GET http://localhost:8000/v1/launches

### 

GET http://localhost:8000/v1/launches?limit=5&page=2

###

POST http://localhost:8000/v1/launches
Content-Type: application/json

{
    "mission": "ZTM155",
    "rocket": "ZTM Experimental IS1",
    "target": "Kepler-1652 b",
    "launchDate": "January 17, 2030"
}

###

DELETE  http://localhost:8000/v1/launches/103

###

GET https://api.spacexdata.com/v4/launches/latest

###


POST https://api.spacexdata.com/v4/launches/query
Content-Type: application/json

{
    "query": { },
    "options" :{
        "pagination": false,
        "populate": [{
            "path": "rocket",
            "select": {
                "name": 1
            }
        }, {
            "path": "payloads",
            "select": {
                "customers": 1
            }
        }]
    }
}